name: "Bug Report"
description: "Report a reproducible bug or error"
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please fill in the form below to help us investigate and fix the issue.

  - type: input
    id: app_version
    attributes:
      label: "App Version"
      placeholder: "e.g., 1.2.0+15"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: "Platform"
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - Desktop
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "How can we see the error ourselves?"
      placeholder: |
        1. Open the app
        2. Go to 'Profile Settings'
        3. Tap on 'Change Avatar'
        4. App crashes
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs & Environment"
      description: "Paste 'flutter doctor -v' or crash logs here."
      render: shell
