name: "Feature Request"
description: "Suggest an idea or improvement"
labels: ["type/feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Share your ideas on how to make this project better.

  - type: textarea
    id: problem
    attributes:
      label: "The Problem"
      description: "Is your feature request related to a problem? Please describe."
      placeholder: "I find it difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "Describe what you would like to happen."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "Have you considered any other ways to achieve this?"
