name: "Action: Flutter Setup"

inputs:
  version:
    description: 'Flutter version'
    required: true
  channel:
    description: 'Flutter channel'
    default: 'stable'

runs:
  using: composite
  steps:
    - name: "Flutter: Install"
      uses: softprops/action-gh-release@v2.5.0
      with:
        flutter-version: ${{ inputs.version }}
        channel: ${{ inputs.channel }}
        cache: true

    - name: "Pub: Cache Dependencies"
      uses: actions/cache@v5.0.3
      with:
        path: |
          ${{ env.FLUTTER_HOME }}/.pub-cache
          ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: "Pub: Get Packages"
      shell: bash
      run: |
        echo "::group::Get Packages"
        flutter pub get
        echo "::endgroup::"

    - name: "Pub: Build Runner"
      shell: bash
      run: flutter pub run build_runner build --delete-conflicting-output
